server:
  port: 9050
logging:
  level:
    root: debug

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: BOOK-SERVICE


  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

